import hashlib
import random
import re
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from typing import Any

import requests

GREENHOUSE_BOARDS = [
    '23andme',
    'sixsense',
    '8x8',
    'abnormalsecurity',
    'accenture',
    'acquia',
    'activecampaign',
    'addepar',
    'adform',
    'adyen',
    'aeva',
    'affirm',
    'agora',
    'airtable',
    'airbnb',
    'algolia',
    'allbirds',
    'alto',
    'amplitude',
    'angi',
    'anomali',
    'anyscale',
    'appcues',
    'applovin',
    'appnexus',
    'appliedintuition',
    'aristanetyworks',
    'armis',
    'asana',
    'ashby',
    'attentive',
    'atrium',
    'autobrains',
    'avalara',
    'away',
    'axon',
    'aztec',
    'babylon',
    'backblaze',
    'bandwidth',
    'bazaarvoice',
    'benchling',
    'betterhelp',
    'betterment',
    'bigcommerce',
    'bigtincan',
    'bindplane',
    'bitgo',
    'blend',
    'blockdaemon',
    'bombora',
    'botify',
    'braze',
    'brex',
    'brighthealthgroup',
    'brightcove',
    'brightsidehealth',
    'built',
    'bumble',
    'butternutbox',
    'buzzfeed',
    'calendly',
    'callrail',
    'carbonhealth',
    'carta',
    'cedar',
    'cerebral',
    'chainalysis',
    'chargebee',
    'checkr',
    'chime',
    'circleci',
    'citrix',
    'clearbit',
    'clearco',
    'clickup',
    'cloudflare',
    'coassemble',
    'cohere',
    'coinbase',
    'color',
    'compass',
    'complex',
    'contentful',
    'contentstack',
    'corelight',
    'coro',
    'crossbeam',
    'crowdstrike',
    'customerio',
    'dailyharvest',
    'databricks',
    'datarobot',
    'datadog',
    'dbtlabs',
    'deel',
    'delighted',
    'demandbase',
    'discord',
    'doordash',
    'domo',
    'drata',
    'druva',
    'duolingo',
    'ebay',
    'elastic',
    'enchantedrock',
    'envoy',
    'etsy',
    'eventbrite',
    'expel',
    'faire',
    'fanduel',
    'fastly',
    'feedvisor',
    'figma',
    'fivetran',
    'flexport',
    'flatiron',
    'floqast',
    'formstack',
    'forter',
    'fullstory',
    'galileo',
    'gem',
    'ginkgobioworks',
    'glossier',
    'gong',
    'goodrx',
    'gopuff',
    'grafana',
    'grammarly',
    'grandrounds',
    'greenhouse',
    'grove',
    'gusto',
    'hashicorp',
    'headspace',
    'heap',
    'highradius',
    'highspot',
    'himshers',
    'hinge',
    'hippo',
    'housecanary',
    'hubspot',
    'humaninterest',
    'hyperscience',
    'idme',
    'imply',
    'innovaccer',
    'instabase',
    'instacart',
    'intercom',
    'ironcladapp',
    'iterable',
    'jellyvision',
    'jellyfish',
    'jumpcloud',
    'kandji',
    'kareo',
    'klaviyo',
    'kustomer',
    'lacework',
    'launchdarkly',
    'lattice',
    'leadiq',
    'lemonade',
    'lendingclub',
    'litmus',
    'lob',
    'logzio',
    'loopio',
    'loom',
    'lyrahealth',
    'marqeta',
    'mavenclinic',
    'mabl',
    'matillion',
    'medallia',
    'medium',
    'mercury',
    'miro',
    'mixpanel',
    'mode',
    'modernhealth',
    'mongodb',
    'moz',
    'mulesoft',
    'namely',
    'narvar',
    'netlify',
    'newrelic',
    'nextdoor',
    'nexthink',
    'nightfall',
    'noom',
    'ns1',
    'nuna',
    'nylas',
    'obsidian',
    'okta',
    'omada',
    'onemedical',
    'onesignal',
    'onfido',
    'opentable',
    'opendoor',
    'optimizely',
    'orca',
    'oscar',
    'outreach',
    'outdoorvoices',
    'ownbackup',
    'oyster',
    'paddle',
    'pagerduty',
    'palantir',
    'patreon',
    'pathai',
    'pendo',
    'perimeter81',
    'personio',
    'phreesia',
    'pipedrive',
    'pinterest',
    'plaid',
    'podium',
    'postman',
    'procore',
    'productboard',
    'qualified',
    'quantummetric',
    'quora',
    'ramp',
    'reddit',
    'redfin',
    'recharge',
    'recurly',
    'relay',
    'remitly',
    'renttherunway',
    'retool',
    'rippling',
    'roblox',
    'robinpowered',
    'robinhood',
    'root',
    'rootly',
    'rubrik',
    'sailpoint',
    'salesloft',
    'scaleai',
    'segment',
    'seismic',
    'sendbird',
    'sendoso',
    'sentry',
    'signifyd',
    'singlestore',
    'sisense',
    'skillz',
    'snyk',
    'sofi',
    'soundcloud',
    'sourcegraph',
    'springhealth',
    'sprinklr',
    'sproutsocial',
    'squarespace',
    'starburst',
    'stitchfix',
    'stripe',
    'surveymonkey',
    'superhuman',
    'tackle',
    'talkdesk',
    'talend',
    'tanium',
    'taskus',
    'tenable',
    'tempus',
    'theathletic',
    'therealreal',
    'thredup',
    'thrivemarket',
    'thumbtack',
    'tipalti',
    'toasttab',
    'tonal',
    'totango',
    'twilio',
    'udemy',
    'uniteus',
    'unqork',
    'uptycs',
    'usertesting',
    'vanta',
    'veeva',
    'vercel',
    'verkada',
    'vidahealth',
    'vimeo',
    'vonage',
    'warbyparker',
    'wayfair',
    'webflow',
    'wealthfront',
    'wandb',
    'whatnot',
    'willowtree',
    'wise',
    'wistia',
    'workato',
    'workiva',
    'writer',
    'xactly',
    'yelp',
    'yotpo',
    'zapier',
    'zendesk',
    'zenput',
    'zerofox',
    'zillow',
    'zocdoc',
    'zoom',
    'zoominfo',
    'zscaler',
    'zuora',
    'accenturefederal',
    'accolade',
    'accruent',
    'activeprospect',
    'adagiohealth',
    'adaptiveinsights',
    'adcellerant',
    'addshoppers',
    'aderant',
    'adeptushealth',
    'adero',
    'adesa',
    'adlucent',
    'admix',
    'adpredictive',
    'adroll',
    'adtheorent',
    'advanceautoparts',
    'aemetis',
    'adventinternational',
    'adventisthealth',
    'aevo',
    'afiniti',
    'aftership',
    'agero',
    'agentsync',
    'agilesports',
    'agreeya',
    'agricola',
    'playags',
    'ahana',
    'aholddelhaize',
    'aidoc',
    'airgain',
    'airtightnetworks',
    'americaninfosource',
    'aiven',
    'akamai',
    'akoya',
    'alarmcom',
    'alertlogic',
    'alertmedia',
    'alida',
    'aligntechnology',
    'alkami',
    'allegiantair',
    'allegis',
    'alliancedata',
    'allscripts',
    'allstate',
    'alpineiq',
    'altusgroup',
    'aluma',
    'amazonadvertising',
    'amberroad',
    'ambrosiabh',
    'amendconsulting',
    'amerilife',
    'amerisave',
    'amperecomputing',
    'amplemarket',
    'amwell',
    'ancestry',
    'ancile',
    'andela',
    'anduin',
    'angelcityfootballclub',
    'anglehealth',
    'answerconnect',
    'anvl',
    'aon',
    'aperiatechnologies',
    'apexfintechsolutions',
    'apixio',
    'apolloio',
    'appdynamics',
    'appian',
    'appomni',
    'apreehealth',
    'apteryx',
    'aptia',
    'aptiviti',
    'aquasecurity',
    'aquant',
    'araize',
    'arborrealty',
    'arcadiapower',
    'archerdx',
    'arcticwolf',
    'arcos',
    'arcsight',
    'aritzia',
    'armor',
    'armoire',
    'armocloud',
    'aro',
    'arramton',
    'arrivelogistics',
    'arterahealth',
    'arya',
    'ascendanalytics',
    'ascendlearning',
    'ascension',
    'ashfieldengage',
    'ashleystewart',
    'aspentech',
    'assuranceiq',
    'assuredallies',
    'assurant',
    'astoundcommerce',
    'asurea',
    'ataccama',
    'atheniumanalytics',
    'athenahealth',
    'atscale',
    'attain',
    'attivo',
    'atturra',
    'audaxgroup',
    'auditboard',
    'auth0',
    'autofi',
    'autokiniton',
    'automatedlogic',
    'automationanywhere',
    'automox',
    'autonation',
    'autorabit',
    'avaaz',
    'avaya',
    'avetta',
    'avocado',
    'axway',
    'backbase',
    'bain',
    'bakkt',
    'balsa',
    'bananarepublic',
    'bandcamp',
    'banjo',
    'barclays',
    'barometric',
    'basis',
    'bausch',
    'bcvsocial',
    'beaconhealthsystem',
    'benevity',
    'berkshiregrey',
    'berryglobal',
    'bettercloud',
    'bigbear',
    'bigpanda',
    'birdeye',
    'bizcraft',
    'blackline',
    'blendlabs',
    'bloomerang',
    'bloomreach',
    'bnymellon',
    'boomi',
    'boompop',
    'bootstraplegal',
    'botco',
    'brainwavescience',
    'bravurasecurity',
    'brazen',
    'brightmountain',
    'brightspot',
    'bringai',
    'brinks',
    'bringg',
    'bristleconeai',
    'broadcom',
    'broadridge',
    'bronto',
    'buildout',
    'businesswire',
    'butterflynetwork',
    'c3',
    'calix',
    'callminer',
    'calyx',
    'camunda',
    'canonical',
    'canto',
    'capellaspace',
    'cardboardbicycle',
    'cardlytics',
    'cargurus',
    'cargo',
    'cartax',
    'casebook',
    'casetext',
    'celigo',
    'centerpointenergy',
    'centricbrands',
    'centrica',
    'cerebras',
    'cerecore',
    'certik',
    'certinia',
    'ceto',
    'chainguard',
    'chariot',
    'chaser',
    'cheetahdigital',
    'chownow',
    'cibc',
    'cigna',
    'circle',
    'circulatecapital',
    'cirium',
    'citadelsecurities',
    'citi',
    'clair',
    'clari',
    'clarityai',
    'clearwater',
    'cleo',
    'closinglock',
    'cloudera',
    'cloudhealth',
    'cloudinary',
    'cloudzero',
    'coalition',
    'cobalt',
    'cockroachlabs',
    'code42',
    'codestream',
    'codility',
    'cogito',
    'cognism',
    'cognosante',
    'coherus',
    'coit',
    'collaborativeai',
    'collectai',
    'collectivehealth',
    'collibra',
    'ycombinator',
    'comeas',
    'commercesignals',
    'communifire',
    'cpegrp',
    'comparably',
    'complementfin',
    'comply365',
    'composable',
    'computacenter',
    'concord',
    'conduit',
    'connectedintelligence',
    'consero',
    'constructivedialogue',
    'contaazul',
    'contentsquare',
    'continuumanalytics',
    'conversant',
    'convoso',
    'copper',
    'cordial',
    'corestack',
    'coreview',
    'cosaic',
    'costar',
    'counsyl',
    'covariant',
    'coveo',
    'covetrus',
    'creatoriq',
    'credibly',
    'creditas',
    'criticalstart',
    'crowdtangle',
    'cues',
    'curalate',
    'cyberhaven',
    'cycognito',
    'cyera',
    'cyncly',
    'cynosure',
    'daisie',
    'danone',
    'darkpulse',
    'dashboard',
    'dassault',
    'dataworld',
    'datafleets',
    'datagrail',
    'dataiku',
    'datakitchen',
    'dataminr',
    'datasette',
    'datastax',
    'datatron',
    'datto',
    'davidenergy',
    'deepmind',
    'definitivehc',
    'degreed',
    'demandware',
    'digicert',
    'digimarc',
    'digitalturbine',
    'dignifyhealth',
    'directtv',
    'dispatch',
    'dispatcher',
    'diversant',
    'divert',
    'divvyhomes',
    'dlocate',
    'doordashdrive',
    'dotmatics',
    'doubleverify',
    'dovercorporation',
    'dreambox',
    'drift',
    'dropbox',
    'duos',
    'dynamoai',
    'e2open',
    'eab',
    'earlysalary',
    'eaton',
    'echelon',
    'econiq',
    'edcor',
    'edgepetrol',
    'edifecs',
    'edisonpartners',
    'educateonline',
    'ekata',
    'elekta',
    'elevatek12',
    'elitetech',
    'elli',
    'ellevationeducation',
    'ellevest',
    'elsevier',
    'emergencecapital',
    'emlogis',
    'empower',
    'encora',
    'endpointclinical',
    'epam',
    'epicor',
    'equinix',
    'equinox',
    'eris',
    'ethoslife',
    'etleap',
    'evolenthealth',
    'exactsciences',
    'execonline',
    'exostar',
    'experian',
    'exponent',
    'expensify',
    'eyevance',
    'fabric',
    'factset',
    'falcon',
    'famousfootwear',
    'feedbackwhiz',
    'feelter',
    'ferc',
    'feverup',
    'fidelity',
    'fieldguide',
    'fieldwire',
    'figure',
    'filamentai',
    'fintechium',
    'firstam',
    'firstlightfiber',
    'five9',
    'flextrade',
    'flipcause',
    'flosum',
    'fmccorporation',
    'forddirect',
    'forerunnerventures',
    'formidable',
    'foursquare',
    'freenovation',
    'freshbooks',
    'frieslandcampina',
    'fubotv',
    'fullpath',
    'funnel',
    'futurefitai',
    'g2',
    'gainsight',
    'galaxydigital',
    'galileofinancial',
    'garnerhealth',
    'gartner',
    'geaviation',
    'geoforce',
    'getaccept',
    'getgo',
    'gigamon',
    'gigpro',
    'glia',
    'glossgenius',
    'gluehome',
    'gocardless',
    'goodwaygroup',
    'google',
    'govos',
    'govpilot',
    'graco',
    'grandcanyonedu',
    'greenpowermotor',
    'gridium',
    'griffin',
    'grover',
    'guidepoint',
    'h2o',
    'halliburton',
    'hang',
    'harbor',
    'harnham',
    'hartehanks',
    'harvard',
    'hatch',
    'hazelhealth',
    'healthedge',
    'healthgrades',
    'healthstream',
    'hearst',
    'heliogen',
    'helium',
    'helmholtz',
    'henryschein',
    'here',
    'hirevue',
    'hivemind',
    'hmshost',
    'homelight',
    'homepoint',
    'honeybeehealth',
    'honeycombio',
    'honor',
    'hotjar',
    'hrms',
    'humana',
    'hungerrush',
    'iamcloud',
    'ibl',
    'iceindustries',
    'icims',
    'idc',
    'iexcloud',
    'ignitetech',
    'ikea',
    'illusivenetworks',
    'impactful',
    'impossiblefoods',
    'improvinghealth',
    'inqtel',
    'incorta',
    'indicina',
    'indigitous',
    'industrydive',
    'informa',
    'infosum',
    'infotrack',
    'inpixon',
    'inscribe',
    'insideout',
    'integralads',
    'intelemage',
    'intelerad',
    'intellicheck',
    'intentful',
    'interplaylearning',
    'intrepidtravel',
    'invoicecloud',
    'irisautomation',
    'ironpaper',
    'ironsource',
    'iteonic',
    'iteris',
    'jamsadr',
    'jane',
    'jitterbit',
    'jobsohio',
    'jobyaviation',
    'joynbio',
    'jrs',
    'jumio',
    'junglescout',
    'khealth',
    'kaleido',
    'kantar',
    'kapital',
    'kaplan',
    'katalon',
    'kcom',
    'keap',
    'kbb',
    'kensho',
    'keyfactor',
    'kiddom',
    'kirasystems',
    'klarna',
    'knowbe4',
    'kowl',
    'krafton',
    'kronosbio',
    'kyndryl',
    'lbrands',
    'lantum',
    'laqos',
    'laseraway',
    'latham',
    'lattimoreblack',
    'laudio',
    'layboard',
    'leanix',
    'leaptools',
    'leandata',
    'learnerbly',
    'learnup',
    'leidos',
    'lev',
    'lever',
    'lexcheck',
    'lightship',
    'lincglobal',
    'linkedin',
    'lingo',
    'linksquares',
    'liqtech',
    'litify',
    'litcapital',
    'livingsocial',
    'lloyds',
    'locustwalk',
    'logically',
    'loginradius',
    'looker',
    'lory',
    'luscii',
    'lumos',
    'machinations',
    'macquarie',
    'magicleap',
    'makerpad',
    'malwarebytes',
    'managednetworks',
    'manifold',
    'mapr',
    'mapbox',
    'marahealth',
    'marchex',
    'maritz',
    'massmutual',
    'matterport',
    'mavericktransportation',
    'mcafee',
    'mccann',
    'mckinsey',
    'measured',
    'medialink',
    'mediamath',
    'medidata',
    'medline',
    'mend',
    'mensante',
    'merge',
    'messagegears',
    'metis',
    'metmox',
    'metricsdirect',
    'mews',
    'mic',
    'microsoft',
    'middlewarehq',
    'mightyhealth',
    'mineraltree',
    'minted',
    'missionlane',
    'mitratech',
    'mobiquity',
    'mobius',
    'modeln',
    'momentive',
    'mondaydotcom',
    'moneylion',
    'montagetalent',
    'morningstar',
    'motive',
    'movella',
    'msci',
    'multiverse',
    'mynd',
    'myriad',
    'narrativescience',
    'navan',
    'navex',
    'nearmap',
    'netsmart',
    'ninjarmm',
    'nodesource',
    'nomissolutions',
    'nomoko',
    'nopileos',
    'novu',
    'nowhealth',
    'nuance',
    'nubank',
    'numbersstation',
    'nurx',
    'nux',
    'nvent',
    'nyble',
    'observablehq',
    'ocient',
    'octus',
    'offshore',
    'ogilvy',
    'olink',
    'onetrust',
    'ontic',
    'openinvest',
    'openview',
    'opower',
    'optiver',
    'oracle',
    'orchestry',
    'origence',
    'orthofi',
    'outbrain',
    'outdoorsy',
    'outliant',
    'outsystems',
    'overdrive',
    'owncompany',
    'peimusselking',
    'pact',
    'paige',
    'papercut',
    'parakeethealth',
    'paramount',
    'parseq',
    'partnerize',
    'patchworkhealth',
    'pathstream',
    'pave',
    'payit',
    'paylocity',
    'paytronix',
    'peoplegrove',
    'peopleready',
    'perch',
    'performante',
    'perimeter',
    'persado',
    'pharmerica',
    'phishingbox',
    'photoshelter',
    'physician360',
    'pingidentity',
    'pipefy',
    'pivotal',
    'platform9',
    'playsight',
    'podimetrics',
    'policygenius',
    'pollinate',
    'polly',
    'ponyai',
    'postclick',
    'predictiveindex',
    'presto',
    'pricespider',
    'primarybid',
    'primerica',
    'primer',
    'processmaker',
    'profilics',
    'promethean',
    'promptcloud',
    'proofpoint',
    'propharma',
    'prove',
    'purestorage',
    'purposeful',
    'qlik',
    'qualtek',
    'quickbase',
    'quinstreet',
    'quotient',
    'radial',
    'radius',
    'rainfall',
    'rapidsos',
    'realtor',
    'realpage',
    'reciprocity',
    'recora',
    'recvue',
    'redventures',
    'registria',
    'relativity',
    'relief',
    'remote',
    'renaissance',
    'renovationangel',
    'reporta',
    'reputation',
    'reprise',
    'responsys',
    'revelsystems',
    'revenue',
    'rexly',
    'rgp',
    'riata',
    'riskalyze',
    'ritual',
    'rivian',
    'roadtripnation',
    'rocket',
    'rockstargames',
    'rollbar',
    'rpalabs',
    'runsignup',
    'runway',
    'safelayer',
    'sagent',
    'salesforce',
    'sama',
    'sanosi',
    'satellite',
    'savingstar',
    'saviynt',
    'scalarhealth',
    'scienceexchange',
    'scisparc',
    'scopely',
    'scorpionco',
    'scoutrfp',
    'seatgeek',
    'seegrid',
    'segmint',
    'semarchy',
    'servicetitan',
    'setpoint',
    'settle',
    'shelter',
    'shogun',
    'shopmonkey',
    'shortcut',
    'showpad',
    'sncorp',
    'signaladvance',
    'signalfd',
    'simco',
    'sitel',
    'sizmek',
    'skykick',
    'smartsheet',
    'smarsh',
    'socure',
    'softserve',
    'solerahealth',
    'sophos',
    'sorcero',
    'spectranetics',
    'spectrotel',
    'spot',
    'spread',
    'springeducation',
    'standardai',
    'starlingbank',
    'starry',
    'stitchdata',
    'stormwind',
    'strands',
    'streamsets',
    'stride',
    'structured',
    'sumologic',
    'sunbit',
    'supportninja',
    'surveylegend',
    'swiftly',
    'swordhealth',
    'sybor',
    'synaptics',
    'synapsefi',
    'synopsys',
    'taboola',
    'tacit',
    'tango',
    'taptica',
    'taxjar',
    'teachable',
    'teamdynamix',
    'techsmith',
    'goteleport',
    'telispire',
    'tennr',
    'terminus',
    'terracon',
    'terrafuse',
    'territoryfoods',
    'textura',
    'thinkdataworks',
    'thirdbridge',
    'thoughtexchange',
    'thread',
    'threespot',
    'thunderhead',
    'timexact',
    'tirehub',
    'titan',
    'togetherwork',
    'tokentransit',
    'toptal',
    'touchnet',
    'trackman',
    'transunion',
    'trendkite',
    'trendsetter',
    'trestle',
    'trinet',
    'triptych',
    'tripadvisor',
    'trueinfluence',
    'trustedhealth',
    'trustengine',
    'tuitionio',
    'turbonomic',
    'turo',
    'twitter',
    'txone',
    'uberflip',
    'ultimatesoftware',
    'ultimus',
    'umbrella',
    'unison',
    'upbound',
    'uplight',
    'uploady',
    'upstart',
    'userpilot',
    'uveye',
    'validity',
    'valon',
    'varex',
    'vastera',
    'vault12',
    'vectorize',
    'venasolutions',
    'velocify',
    'venturelane',
    'verifyu',
    'velocityehs',
    'ridewithvia',
    'vidmob',
    'viewlift',
    'virtahealth',
    'virtusa',
    'virsec',
    'visuallease',
    'vitals',
    'voiceops',
    'voltinformation',
    'votiv',
    'vroom',
    'vtugroup',
    'vwo',
    'walkersands',
    'wallaroo',
    'wallbox',
    'walmart',
    'watchguard',
    'watermarkinsights',
    'watershed',
    'wellsky',
    'wex',
    'whiparound',
    'whisper',
    'whiteboard',
    'widen',
    'wilio',
    'windriver',
    'wisersolutions',
    'withings',
    'wm',
    'wobot',
    'wonolo',
    'woocommerce',
    'workspot',
    'workstream',
    'worldly',
    'wrike',
    'x4pharma',
    'xplor',
    'yardstick',
    'yext',
    'yipitdata',
    'yield',
    'yours',
    'yubico',
    'zealforwork',
    'zenoss',
    'zepto',
    'zetaglobal',
    'zevia',
    'zinniahealth',
    'flyzipline',
    'zoho',
    'zonehaven',
    'zurich'
]

ALLOWED_TITLE_KEYWORDS = [
    "data analyst",
    "business analyst",
    "bi analyst",
    "reporting analyst",
    "business intelligence analyst",
    "analytics engineer",
    "product analyst",
    "marketing analyst",
    "operations analyst",
    "insights analyst",
    "decision scientist",
    "data analytics analyst",
    "commercial analyst",
    "financial analyst",
    "pricing analyst",
    "risk analyst",
    "strategy analyst",
]

BLOCKED_TITLE_KEYWORDS = [
    "data engineer",
    "machine learning engineer",
    "ml engineer",
    "software engineer",
    "ai engineer",
    "architect",
    "recruiter",
    "talent",
    "designer",
    "frontend",
    "backend",
    "full stack",
    "devops",
    "site reliability",
    "sre",
]

SENIOR_BLOCKERS = [
    "staff",
    "principal",
    "director",
    "manager",
    "head of",
    "vice president",
    "vp",
]

_SENIOR_BLOCKER_RE = re.compile(
    r'\b(staff|principal|director|manager|head of|vice president|vp)\b',
    re.IGNORECASE,
)

ALLOWED_LOCATION_KEYWORDS = [
    "united states",
    "usa",
    "us",
    "remote",
    "new york",
    "california",
    "texas",
    "florida",
    "illinois",
    "washington",
    "massachusetts",
    "virginia",
    "georgia",
    "north carolina",
    "michigan",
    "new jersey",
    "pennsylvania",
    "ohio",
    "arizona",
    "colorado",
]

BLOCKED_LOCATION_KEYWORDS = [
    "india",
    "mexico",
    "canada",
    "brazil",
    "argentina",
    "germany",
    "france",
    "spain",
    "italy",
    "poland",
    "netherlands",
    "singapore",
    "philippines",
    "australia",
    "japan",
    "ireland",
    "united kingdom",
    "uk",
]

REQUEST_TIMEOUT_SECONDS = 20
GREENHOUSE_WORKERS = 10
MAX_BOARDS_PER_RUN = 50


def make_external_id(job: dict[str, Any], board: str) -> str:
    raw = (
        str(job.get("id") or "").strip()
        or str(job.get("absolute_url") or "").strip()
        or f"{board}_{job.get('title', '')}"
    )
    return "greenhouse_" + hashlib.md5(raw.encode("utf-8")).hexdigest()


def parse_posted_at(value: Any):
    if not value:
        return None

    if isinstance(value, datetime):
        return value.replace(tzinfo=None) if value.tzinfo else value

    try:
        text = str(value).strip()
        if text.endswith("Z"):
            text = text.replace("Z", "+00:00")
        dt = datetime.fromisoformat(text)
        return dt.replace(tzinfo=None) if dt.tzinfo else dt
    except Exception:
        return None


def is_allowed_title(title: str) -> bool:
    if not title:
        return False

    t = title.strip().lower()

    if any(bad in t for bad in BLOCKED_TITLE_KEYWORDS):
        return False

    if _SENIOR_BLOCKER_RE.search(t):
        return False

    if "analytics engineer" in t:
        return True

    return any(good in t for good in ALLOWED_TITLE_KEYWORDS)


def is_allowed_location(location: str) -> bool:
    if not location or location.strip().lower() in ("unknown", ""):
        return True

    loc = location.strip().lower()

    if any(bad in loc for bad in BLOCKED_LOCATION_KEYWORDS):
        return False

    if any(good in loc for good in ALLOWED_LOCATION_KEYWORDS):
        return True

    return False


def build_location(job: dict[str, Any]) -> str:
    location = (job.get("location", {}) or {}).get("name", "")
    location = str(location).strip()

    if not location:
        location = "Unknown"

    return location


def normalize_greenhouse_job(job: dict[str, Any], board: str) -> dict[str, Any] | None:
    title = (job.get("title") or "").strip()
    if not is_allowed_title(title):
        return None

    url = (job.get("absolute_url") or "").strip()
    if not url:
        return None

    location = build_location(job)
    if not is_allowed_location(location):
        return None

    metadata = job.get("metadata") or []
    metadata_text = " | ".join(
        f"{m.get('name', '')}: {m.get('value', '')}"
        for m in metadata
        if isinstance(m, dict)
    ).strip()

    content = (job.get("content") or "").strip()
    description = content if content else metadata_text

    posted_at = (
        parse_posted_at(job.get("updated_at"))
        or parse_posted_at(job.get("created_at"))
    )

    company = board.replace("-", " ").title()

    return {
        "external_id": make_external_id(job, board),
        "title": title,
        "company": company,
        "location": location,
        "url": url,
        "source": "greenhouse",
        "description": description[:4000],
        "posted_at": posted_at,
    }


def _fetch_one_greenhouse(board: str) -> list[dict[str, Any]]:
    url = f"https://boards-api.greenhouse.io/v1/boards/{board}/jobs?content=true"

    try:
        response = requests.get(url, timeout=REQUEST_TIMEOUT_SECONDS)

        if response.status_code == 404:
            print(f"⚠️ Greenhouse board not found: {board}", flush=True)
            return []

        response.raise_for_status()

        payload = response.json()
        raw_jobs = payload.get("jobs", [])

        print(f"Greenhouse fetched {len(raw_jobs)} raw jobs for {board}", flush=True)

        out = []
        for raw_job in raw_jobs:
            normalized = normalize_greenhouse_job(raw_job, board)
            if normalized:
                out.append(normalized)

        return out

    except requests.HTTPError as e:
        print(f"⚠️ Greenhouse HTTP error for {board}: {e}", flush=True)
        return []
    except requests.RequestException as e:
        print(f"⚠️ Greenhouse request failed for {board}: {e}", flush=True)
        return []
    except Exception as e:
        print(f"⚠️ Greenhouse failed for {board}: {e}", flush=True)
        return []


def fetch_greenhouse_jobs() -> list[dict[str, Any]]:
    all_results: list[dict[str, Any]] = []
    seen_keys: set[tuple[str, str]] = set()
    lock = threading.Lock()

    boards_to_check = random.sample(
        GREENHOUSE_BOARDS,
        min(MAX_BOARDS_PER_RUN, len(GREENHOUSE_BOARDS))
    )

    print(
        f"🚀 Greenhouse refresh starting | boards_this_run={len(boards_to_check)} | "
        f"workers={GREENHOUSE_WORKERS}",
        flush=True
    )

    with ThreadPoolExecutor(max_workers=GREENHOUSE_WORKERS) as executor:
        futures = {
            executor.submit(_fetch_one_greenhouse, board): board
            for board in boards_to_check
        }

        for future in as_completed(futures):
            board = futures[future]
            try:
                jobs = future.result()
            except Exception as e:
                print(f"⚠️ Greenhouse future failed for {board}: {e}", flush=True)
                continue

            with lock:
                for job in jobs:
                    key = (job["external_id"], job["source"])
                    if key not in seen_keys:
                        seen_keys.add(key)
                        all_results.append(job)

    print(f"✅ Greenhouse normalized jobs count = {len(all_results)}", flush=True)
    return all_results