import hashlib
import random
from datetime import datetime
from typing import Any

import requests

LEVER_COMPANIES = [
    '1password',
    '2u',
    '3playmedia',
    '5nine',
    '6sense',
    '8thlight',
    'abacus',
    'abbottlaboratories',
    'abilitynetwork',
    'accenture',
    'accolade',
    'acimacredit',
    'aclima',
    'acloudguru',
    'acquia',
    'actioniq',
    'acumen',
    'adalo',
    'adaptivebiotech',
    'addepar',
    'addshoppers',
    'adform',
    'adgile',
    'adhoc',
    'adjust',
    'admix',
    'adobe',
    'adparlor',
    'adroll',
    'adstream',
    'adzerk',
    'aeva',
    'affinity',
    'agero',
    'agoric',
    'aharooms',
    'ahoy',
    'airbase',
    'airgain',
    'airkit',
    'airtable',
    'alchemyapi',
    'algolia',
    'alida',
    'alkira',
    'alloy',
    'allturtles',
    'alma',
    'alphasense',
    'altruist',
    'altsea',
    'amazon',
    'ambientclinical',
    'ambrook',
    'amplitude',
    'analyticpartners',
    'angellist',
    'angi',
    'anomalo',
    'anthropic',
    'aon',
    'apollographql',
    'applied',
    'appliedsystems',
    'aptly',
    'apttus',
    'arcadia',
    'archie',
    'argoai',
    'arkosego',
    'armorblox',
    'arrantabio',
    'array',
    'arrivelogistics',
    'artera',
    'artisan',
    'aryaka',
    'asa',
    'asgn',
    'assembled',
    'assuranceiq',
    'astoundcommerce',
    'atelio',
    'atheneum',
    'athos',
    'atlassian',
    'atriumhealth',
    'atto',
    'attuneinsurance',
    'auble',
    'aurishealth',
    'auth0',
    'autobooks',
    'autofi',
    'automattic',
    'avant',
    'avetta',
    'avochato',
    'axelar',
    'ayasdi',
    'backdrop',
    'balance',
    'balena',
    'bandwidth',
    'banjohealth',
    'barrel',
    'basistech',
    'bazaarvoice',
    'bcvsocial',
    'bench',
    'benchling',
    'betterment',
    'bevy',
    'bigpanda',
    'binti',
    'bioatla',
    'bioptigen',
    'bird',
    'bitrise',
    'blackboard',
    'blade',
    'blend',
    'blockfi',
    'bloomreach',
    'blueapron',
    'bluebeam',
    'bluecat',
    'bluevine',
    'boku',
    'bolster',
    'bonterra',
    'boomtownroi',
    'boostedcommerce',
    'boxed',
    'boxtone',
    'brafton',
    'brainpop',
    'branch',
    'brandfolder',
    'braver',
    'breezy',
    'brightcove',
    'brightedge',
    'brightly',
    'broadlume',
    'bromium',
    'bt',
    'buildium',
    'bumble',
    'buoyant',
    'cachefly',
    'calm',
    'candidco',
    'canopytax',
    'canva',
    'carbon',
    'carrotfertility',
    'cascada',
    'cascadeapp',
    'casebookpbc',
    'casecommons',
    'catalist',
    'catalyze',
    'catapult',
    'celtra',
    'cerbos',
    'cevo',
    'channeladvisor',
    'chaparralenergy',
    'checkbook',
    'chef',
    'cherwell',
    'chilipiper',
    'chord',
    'chronicle',
    'chronosphere',
    'cigna',
    'cin7',
    'circle',
    'circleci',
    'citadel',
    'cityblock',
    'clarifai',
    'clarifyhealth',
    'cleanly',
    'clearbit',
    'clearcover',
    'clearlake',
    'clearscore',
    'clevertap',
    'clipboardhealth',
    'close',
    'clumio',
    'coalition',
    'cobalt',
    'coda',
    'coenterprise',
    'cognitivescale',
    'collabrahealth',
    'collectivehealth',
    'collibra',
    'color',
    'comcasttechnologysolutions',
    'conduent',
    'confiant',
    'confluent',
    'connectwise',
    'contentful',
    'contentsquare',
    'contractlogix',
    'conversica',
    'convey',
    'conviva',
    'cookpad',
    'corteva',
    'corvusinsurance',
    'coupa',
    'courant',
    'coursera',
    'covetrus',
    'craft',
    'crexi',
    'cribl',
    'crit',
    'crosslake',
    'crossriverbank',
    'crunchbase',
    'cubic',
    'cumulusnetworks',
    'curalate',
    'currenhealth',
    'current',
    'customerio',
    'cutover',
    'cvo',
    'cyberark',
    'cylehealth',
    'dailypay',
    'dandi',
    'dandy',
    'dashlane',
    'databricks',
    'datadvantage',
    'dataminr',
    'datasaur',
    'dataworld',
    'datazoom',
    'dave',
    'dbtlabs',
    'dealersocket',
    'dealpath',
    'decibel',
    'decodedhealth',
    'deepgram',
    'deloitte',
    'demisto',
    'dentalintelligence',
    'devo',
    'dialpad',
    'didit',
    'diligent',
    'discord',
    'dispatch',
    'dispatcherapp',
    'divvyhomes',
    'dnb',
    'doctorondemand',
    'dolby',
    'dominodatalab',
    'domo',
    'dragonfly',
    'dronedeploy',
    'dropbox',
    'drw',
    'duckduckgo',
    'easyship',
    'ecovadis',
    'edgeconnex',
    'edtechimpact',
    'elastic',
    'elationhealth',
    'elevate',
    'ellevationeducation',
    'embroker',
    'emogi',
    'empower',
    'enable',
    'encode',
    'encourage',
    'endear',
    'endpointai',
    'engage3',
    'enginecommerce',
    'entrust',
    'envistacom',
    'eqtpartners',
    'equisoft',
    'equussoftware',
    'espresa',
    'ethoslife',
    'eventfarm',
    'everbridge',
    'everlaw',
    'evidentid',
    'ezra',
    'fabfitfun',
    'fabric',
    'facteus',
    'fairwaync',
    'featurespace',
    'fieldwire',
    'figma',
    'finicity',
    'firstbase',
    'fiserv',
    'fisherinvestments',
    'fitbit',
    'flatfile',
    'fleetcomplete',
    'flexe',
    'flip',
    'flirtey',
    'floqast',
    'flyzipline',
    'formassembly',
    'formation',
    'formlabs',
    'forrester',
    'foursquare',
    'frameworklaptop',
    'funnelleasing',
    'gainsight',
    'galley',
    'gamma',
    'gap',
    'gartner',
    'gem',
    'genuity',
    'getcensus',
    'getclockwise',
    'getshogun',
    'github',
    'gitlab',
    'gladly',
    'glossgenius',
    'go1',
    'gohealth',
    'gong',
    'goodleap',
    'gopuff',
    'goraft',
    'grammarly',
    'grandroundshealth',
    'greenhouse',
    'grid',
    'grovecollaborative',
    'grow',
    'grubhub',
    'guardanthealth',
    'guildeducation',
    'guru',
    'gusto',
    'gyant',
    'hackerone',
    'halo',
    'happymoney',
    'hashicorp',
    'hawkeye360',
    'headway',
    'heap',
    'heliogen',
    'hellodigit',
    'helm',
    'helpscout',
    'higherlogic',
    'hightouch',
    'hippo',
    'honehq',
    'honest',
    'hootsuite',
    'hopper',
    'huckberry',
    'humanapi',
    'humanly',
    'hypr',
    'ibotta',
    'ideascale',
    'ignitionapp',
    'igrafx',
    'impartner',
    'incountry',
    'indiegogo',
    'inmobi',
    'innoflight',
    'innovid',
    'insellerate',
    'insomniac',
    'inspectify',
    'integrity',
    'intentwise',
    'interfolio',
    'intervalhealth',
    'invisionapp',
    'ipgmediabrands',
    'iqstel',
    'irhythm',
    'iteratively',
    'jamasoftware',
    'jcrew',
    'jellysmack',
    'jff',
    'jiraalign',
    'joinhandshake',
    'joinhomebase',
    'jotform',
    'juniper',
    'justworks',
    'karat',
    'kargo',
    'kasasa',
    'katanamrp',
    'keeptruckin',
    'keyfactor',
    'kickstarter',
    'kindbody',
    'kinetiq',
    'knowable',
    'knowbe4',
    'kohls',
    'kontoorbrands',
    'kustomer',
    'latch',
    'lattice',
    'launchdarkly',
    'launchpadlab',
    'lawgeex',
    'layr',
    'leadsquared',
    'legalzoom',
    'lexalytics',
    'lexico',
    'lightforce',
    'limebike',
    'linear',
    'liveramp',
    'logmein',
    'looker',
    'lyft',
    'm1finance',
    'madkudu',
    'magnetar',
    'mainstream',
    'mamamoney',
    'manifoldmarkets',
    'marigoldhealth',
    'marionete',
    'masterworks',
    'matillion',
    'mavenclinic',
    'mckesson',
    'medidata',
    'mentorcollective',
    'mercury',
    'meruhealth',
    'metarouter',
    'microstrategy',
    'mimecast',
    'mindbridge',
    'miro',
    'modeanalytics',
    'modelbit',
    'modernanimal',
    'moderntreasury',
    'montagetalent',
    'motif',
    'motorefi',
    'multiverse',
    'mural',
    'narvar',
    'nayya',
    'nearmap',
    'netflix',
    'netlify',
    'nextgen',
    'niantic',
    'niche',
    'nimbella',
    'nines',
    'noom',
    'noredink',
    'notco',
    'notion',
    'novu',
    'numerator',
    'nutanix',
    'nuvei',
    'oceanbase',
    'octave',
    'okendo',
    'omadahealth',
    'opaque',
    'openai',
    'opengov',
    'openx',
    'optiver',
    'orca',
    'osaro',
    'oscar',
    'outbrain',
    'owletcare',
    'ownlocal',
    'paigeai',
    'paladinlabs',
    'pandora',
    'paperwork',
    'paramount',
    'particle',
    'patternenergy',
    'pave',
    'paylocity',
    'payscape',
    'paytronix',
    'pendo',
    'peopleai',
    'pepsico',
    'percipientai',
    'phenompeople',
    'piazza',
    'pietrastudio',
    'pillar',
    'pindrop',
    'pitchbook',
    'pixlr',
    'plaid',
    'planet',
    'planful',
    'plangrid',
    'playco',
    'playvs',
    'podio',
    'policygenius',
    'pomelo',
    'portworx',
    'postanalog',
    'powder',
    'previse',
    'priorilegal',
    'procore',
    'producthunt',
    'productiv',
    'profileprint',
    'proofgov',
    'proofpoint',
    'propel',
    'protagonist',
    'prowritingaid',
    'pusher',
    'quickmed',
    'quilt',
    'qumulo',
    'quora',
    'radar',
    'radiclehealth',
    'rakutenadvertising',
    'ramp',
    'ravemobilesafety',
    'realm',
    'rechargepayments',
    'recruitics',
    'recurly',
    'reddit',
    'redoxengine',
    'refinery29',
    'relayfi',
    'replicant',
    'reservetrust',
    'resiliosync',
    'retailready',
    'ribbitnetwork',
    'rigup',
    'ripple',
    'risq',
    'robinhoodmarkets',
    'rootstock',
    'route',
    'ruggable',
    'saama',
    'safetyculture',
    'sardine',
    'saucelabs',
    'scaleai',
    'scaledagile',
    'schoox',
    'scopely',
    'scratch',
    'seatgeek',
    'securonix',
    'seedfi',
    'seegrid',
    'selectquote',
    'semaphoreci',
    'servicemax',
    'shift',
    'shipt',
    'shortcut',
    'silamoney',
    'simplr',
    'simspace',
    'skuid',
    'skydio',
    'skytap',
    'slack',
    'slice',
    'smarsh',
    'smithrx',
    'snowflake',
    'socure',
    'softkinetic',
    'solarwinds',
    'solovis',
    'sourcepoint',
    'splashtop',
    'spread',
    'springhealth',
    'square',
    'squarespace',
    'stockx',
    'streamyard',
    'substack',
    'sunderenergy',
    'sunrisetech',
    'supercell',
    'supertab',
    'swimlane',
    'swordhealth',
    'synaptic',
    'sysdig',
    'tableau',
    'tackle',
    'tandem',
    'tangocard',
    'tapad',
    'tara',
    'targetbase',
    'taxbit',
    'teachable',
    'techhire',
    'tekion',
    'tempest',
    'terminus',
    'terra',
    'thatch',
    'thermofisher',
    'thetradedesk',
    'thoughtworks',
    'ticketmaster',
    'tipalti',
    'toasttab',
    'tonkean',
    'tophire',
    'topsort',
    'toroidal',
    'traceableai',
    'transfix',
    'transunion',
    'tricentis',
    'triptease',
    'trucordia',
    'trueaccord',
    'truecommerce',
    'truora',
    'trycaviar',
    'tulip',
    'tunein',
    'turnitin',
    'twilio',
    'twinstarcu',
    'twitter',
    'tyson',
    'udacity',
    'unacast',
    'unison',
    'uniteus',
    'upliftingathletes',
    'upstart',
    'useanvil',
    'usebutton',
    'useorigin',
    'userflow',
    'validity',
    'varex',
    'vast',
    'veem',
    'velocityglobal',
    'vera',
    'vibrant',
    'visier',
    'visionaryintegration',
    'vitalsource',
    'voxel51',
    'vroom',
    'wallaroo',
    'warnermedia',
    'watchguard',
    'watershed',
    'webflow',
    'wellhub',
    'wex',
    'wexhealth',
    'whatnot',
    'whatsapp',
    'whisper',
    'windfall',
    'wingstop',
    'wipro',
    'wistia',
    'withpersona',
    'wonderschool',
    'work-bench',
    'workato',
    'worldsbeyond',
    'writer',
    'xactly',
    'xero',
    'yelp',
    'yext',
    'yotpo',
    'yugalabs',
    'zapier',
    'zelis',
    'zendesk',
    'zenput',
    'zerto',
    'zillow',
    'zoom',
    'zoominfo',
    'zuora'
]

MAX_COMPANIES_PER_RUN = 80
companies_to_check = random.sample(
    LEVER_COMPANIES,
    min(MAX_COMPANIES_PER_RUN, len(LEVER_COMPANIES))
)

ALLOWED_TITLE_KEYWORDS = [
    "data analyst",
    "business analyst",
    "bi analyst",
    "reporting analyst",
    "business intelligence analyst",
    "analytics engineer",
    "product analyst",
    "marketing analyst",
    "operations analyst",
    "insights analyst",
    "decision scientist",
    "data analytics analyst",
    "commercial analyst",
    "financial analyst",
    "pricing analyst",
    "risk analyst",
    "strategy analyst",
]

BLOCKED_TITLE_KEYWORDS = [
    "data engineer",
    "machine learning engineer",
    "ml engineer",
    "software engineer",
    "ai engineer",
    "architect",
    "recruiter",
    "talent",
    "designer",
    "frontend",
    "backend",
    "full stack",
    "devops",
    "site reliability",
    "sre",
]

SENIOR_BLOCKERS = [
    "staff",
    "principal",
    "director",
    "manager",
    "head of",
    "vice president",
    "vp ",
]

ALLOWED_LOCATION_KEYWORDS = [
    "united states",
    "usa",
    "us",
    "remote",
    "new york",
    "california",
    "texas",
    "florida",
    "illinois",
    "washington",
    "massachusetts",
    "virginia",
    "georgia",
    "north carolina",
    "michigan",
    "new jersey",
    "pennsylvania",
    "ohio",
    "arizona",
    "colorado",
]

BLOCKED_LOCATION_KEYWORDS = [
    "india",
    "mexico",
    "canada",
    "brazil",
    "argentina",
    "germany",
    "france",
    "spain",
    "italy",
    "poland",
    "netherlands",
    "singapore",
    "philippines",
    "australia",
    "japan",
    "ireland",
    "united kingdom",
    "uk",
]

REQUEST_TIMEOUT_SECONDS = 20


def make_external_id(job: dict[str, Any], company_slug: str) -> str:
    raw = (
        str(job.get("id") or "").strip()
        or str(job.get("hostedUrl") or "").strip()
        or f"{company_slug}_{job.get('text', '')}"
    )
    return "lever_" + hashlib.md5(raw.encode("utf-8")).hexdigest()


def parse_posted_at(value: Any):
    if not value:
        return None

    try:
        if isinstance(value, (int, float)):
            if value > 10_000_000_000:
                return datetime.utcfromtimestamp(value / 1000)
            return datetime.utcfromtimestamp(value)

        text = str(value).strip()
        if text.isdigit():
            num = int(text)
            if num > 10_000_000_000:
                return datetime.utcfromtimestamp(num / 1000)
            return datetime.utcfromtimestamp(num)

        if text.endswith("Z"):
            text = text.replace("Z", "+00:00")

        dt = datetime.fromisoformat(text)
        return dt.replace(tzinfo=None) if dt.tzinfo else dt
    except Exception:
        return None


def is_allowed_title(title: str) -> bool:
    if not title:
        return False

    t = title.strip().lower()

    if any(bad in t for bad in BLOCKED_TITLE_KEYWORDS):
        return False

    if any(bad in t for bad in SENIOR_BLOCKERS):
        return False

    if "analytics engineer" in t:
        return True

    return any(good in t for good in ALLOWED_TITLE_KEYWORDS)


def is_allowed_location(location: str) -> bool:
    if not location:
        return False

    loc = location.strip().lower()

    if any(bad in loc for bad in BLOCKED_LOCATION_KEYWORDS):
        return False

    if any(good in loc for good in ALLOWED_LOCATION_KEYWORDS):
        return True

    return False


def build_location(job: dict[str, Any]) -> str:
    categories = job.get("categories") or {}
    location = (categories.get("location") or "").strip()

    if not location:
        location = "Unknown"

    return location


def normalize_lever_job(job: dict[str, Any], company_slug: str) -> dict[str, Any] | None:
    title = (job.get("text") or "").strip()
    if not is_allowed_title(title):
        return None

    url = (job.get("hostedUrl") or "").strip()
    if not url:
        return None

    description = (
        (job.get("descriptionPlain") or "").strip()
        or (job.get("description") or "").strip()
        or ""
    )

    location = build_location(job)
    if not is_allowed_location(location):
        return None

    posted_at = (
        parse_posted_at(job.get("createdAt"))
        or parse_posted_at(job.get("updatedAt"))
    )

    company = company_slug.replace("-", " ").title()

    return {
        "external_id": make_external_id(job, company_slug),
        "title": title,
        "company": company,
        "location": location,
        "url": url,
        "source": "lever",
        "description": description[:4000],
        "posted_at": posted_at,
    }


def fetch_lever_jobs() -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    seen_keys: set[tuple[str, str]] = set()

    for company_slug in companies_to_check:
        url = f"https://api.lever.co/v0/postings/{company_slug}?mode=json"

        try:
            response = requests.get(url, timeout=REQUEST_TIMEOUT_SECONDS)

            if response.status_code == 404:
                print(f"ℹ️ Lever board not found for {company_slug} (404)", flush=True)
                continue

            response.raise_for_status()

            jobs = response.json()
            if not isinstance(jobs, list):
                jobs = []

            print(f"Lever fetched {len(jobs)} raw jobs for {company_slug}", flush=True)

            for raw_job in jobs:
                normalized = normalize_lever_job(raw_job, company_slug)
                if not normalized:
                    continue

                key = (normalized["external_id"], normalized["source"])
                if key in seen_keys:
                    continue

                seen_keys.add(key)
                results.append(normalized)

        except requests.exceptions.HTTPError as e:
            print(f"⚠️ Lever HTTP error for {company_slug}: {e}", flush=True)
        except requests.exceptions.RequestException as e:
            print(f"⚠️ Lever request failed for {company_slug}: {e}", flush=True)
        except Exception as e:
            print(f"⚠️ Lever failed for {company_slug}: {e}", flush=True)

    print(f"✅ Lever normalized jobs count = {len(results)}", flush=True)
    return results
